Fix errors
Cyberuben/node-postcode pull request #2
Opened 2018-11-26 07:58 UTC by christiaanwesterbeek

2018-11-26 09:47 UTC, Cyberuben commented
I still see a lot of whitespace issues. Please solve this, I'll add eslint config later on and fix the coding style to be more uniform.

2018-11-27 07:47 UTC, christiaanwesterbeek commented
I'm not really interested to fix whitespaces. It was my editor that removed trailing spaces and added a trailing enter at the end of the files. I'll leave it up to you to take it from here.

2020-04-20 09:22 UTC, christiaanwesterbeek commented
The whitespace issues are now solved

2020-04-20 09:43 UTC, Cyberuben requested changes

2020-04-20 09:43 UTC, Cyberuben commented on src/request.js
> +                            reject(err)
This still has whitespace issues

2020-04-20 09:43 UTC, Cyberuben commented on test/test.js
> +                var client = new PostcodeClient({
This block still has whitespace issues

2020-04-20 09:52 UTC, merged

2020-04-20 09:52 UTC, Cyberuben commented
I'll fix it myself, takes too long

2020-04-20 09:58 UTC, Cyberuben commented
https://www.npmjs.com/package/node-postcode

Published to npm